### ISSUE TITLE
Outated version in appdata

### ISSUE THREAD

**Issue by Erick555** [flathub/org.kde.digikam#14]
Flatpak metadata shows version as `7.0.0-rc`. This is due to upstream [stopped updating](https://invent.kde.org/graphics/digikam/-/blob/master/core/app/main/org.kde.digikam.appdata.xml#L619) it at some point. I think downstream patch should be made until it's fixed on upstream side.

**Comment by tsdgeos** [comment]
I'd prefer you send a patch upstream first :)

**Comment by mamoit** [comment]
I opened this issue for the first time 5min ago, and apparently, 12h ago [it has been fixed upstream](https://invent.kde.org/graphics/digikam/-/commit/8049b6070d51bdef068c02a20f559e43e8c1f280) :)

**Comment by edisso10018** [comment]
This page

[https://flathub.org/apps/details/org.kde.digikam](url)

still shows 7.0.0rc from December 26th, 2020. So which version is installed if I install from flathub?

**Comment by Erick555** [comment]
Flathub is at [7.1.0](https://github.com/flathub/org.kde.digikam/blob/8fca90cd6a23de0e0aea9729030511907d5fe16c/org.kde.digikam.json#L66). Metadata bug was fixed upstream but not in package
